export const metadata = {
  title: "Privacy Policy — Reins Realty",
  description: "How Reins Realty collects, uses, and protects personal data, in line with Kenya's Data Protection Act, 2019.",
};

/**
 * Public, unauthenticated privacy notice — required both for the APKPure
 * listing (which asks for a privacy policy URL) and, more fundamentally,
 * because this platform processes tenant PII on behalf of landlord
 * customers and Kenya's Data Protection Act, 2019 requires a data notice
 * for that. Placeholders ([...]) mark facts only the business itself can
 * supply (registered address, phone, ODPC registration number) -- do not
 * remove the brackets or invent values for them.
 */
export default function PrivacyPolicyPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-12">
      <article className="prose prose-sm max-w-none prose-headings:text-ink prose-a:text-ink">
        <h1>Privacy Policy</h1>
        <p className="text-sm text-silver-dark">Last updated: 29 August 2026</p>

        <p>
          This Privacy Policy explains how <strong>Reins Realty</strong> (trading as Robust Rental Platform, operated by
          Reinstrade, &ldquo;we&rdquo;, &ldquo;us&rdquo;) collects, uses, shares, and protects personal data when you use our rental
          management platform (the &ldquo;Platform&rdquo;), whether through our website, our Android app, or our desktop
          app.
        </p>
        <p>
          We process personal data in line with Kenya&rsquo;s <strong>Data Protection Act, 2019</strong> and its
          regulations. If you are in another jurisdiction, other laws may also apply to you.
        </p>

        <h2>1. Who this policy covers</h2>
        <p>This policy applies to three kinds of people who interact with the Platform:</p>
        <ul>
          <li>
            <strong>Landlords and agents</strong> (&ldquo;Customers&rdquo;) who sign up for an account to manage their
            properties.
          </li>
          <li>
            <strong>Customers&rsquo; staff</strong> — property managers, caretakers, and other team members a Customer
            invites onto their account.
          </li>
          <li>
            <strong>Tenants and vendors</strong> whose information a Customer enters into the Platform in order to
            manage a tenancy, lease, or repair job. We process this data as a processor acting on the Customer&rsquo;s
            instructions — the Customer remains responsible for having a lawful basis to give us that data in the
            first place (for example, because it&rsquo;s needed to perform a tenancy agreement).
          </li>
        </ul>

        <h2>2. What we collect</h2>
        <ul>
          <li>
            <strong>Account data</strong>: name, email address, phone number, password (stored hashed, never in
            plain text), and role within an organization.
          </li>
          <li>
            <strong>Property and tenancy data</strong>: property and unit details, lease terms, rent amounts, and
            billing history entered by a Customer or their staff.
          </li>
          <li>
            <strong>Tenant and vendor data</strong>: name, phone number, email address, and — where a Customer
            records it — identification details, lease signatures, and payment history.
          </li>
          <li>
            <strong>Payment data</strong>: M-Pesa transaction references, amounts, and payment status. We do not
            collect or store full payment card numbers or M-Pesa PINs — M-Pesa transactions are processed directly
            by Safaricom.
          </li>
          <li>
            <strong>Communications</strong>: messages sent through the Platform&rsquo;s messaging feature, and the
            content of notices (including eviction notices) generated by the Platform.
          </li>
          <li>
            <strong>Device and usage data</strong>: IP address, browser/device type, and basic usage logs, collected
            automatically for security and reliability purposes.
          </li>
        </ul>

        <h2>3. Why we process this data</h2>
        <p>We process personal data for the following purposes, each with a lawful basis under the Act:</p>
        <ul>
          <li>
            <strong>To provide the Platform</strong> — creating accounts, managing properties and leases, billing
            and payment reconciliation, generating receipts, statements, and lease agreements. (Performance of a
            contract with the Customer.)
          </li>
          <li>
            <strong>To send notices and communications</strong> — payment reminders, receipts, and, where a Customer
            initiates it, formal notices such as an eviction notice, sent by email or WhatsApp. (Performance of a
            contract; legal obligation, where a notice is a statutory requirement.)
          </li>
          <li>
            <strong>To comply with the law</strong> — including tax, financial record-keeping, and tenancy law
            obligations. (Legal obligation.)
          </li>
          <li>
            <strong>To keep the Platform secure and working</strong> — fraud prevention, debugging, and service
            reliability. (Legitimate interest, balanced against your rights.)
          </li>
          <li>
            <strong>To improve the Platform</strong> — understanding how features are used, in aggregated or
            anonymized form wherever possible. (Legitimate interest.)
          </li>
        </ul>

        <h2>4. Who we share data with</h2>
        <p>We do not sell personal data. We share it only where necessary to run the Platform:</p>
        <ul>
          <li>
            <strong>Safaricom (M-Pesa)</strong>, to process rent payments and payouts.
          </li>
          <li>
            <strong>WhatsApp (Meta)</strong>, where a Customer chooses to send a receipt, statement, or notice via a
            WhatsApp link.
          </li>
          <li>
            <strong>Our hosting and infrastructure providers</strong> (currently Vercel for application hosting and
            Turso for database hosting), who process data on our behalf under their own data processing terms.
            These providers may store data on servers outside Kenya; where that happens, we rely on contractual
            safeguards consistent with the Act&rsquo;s cross-border transfer requirements.
          </li>
          <li>
            <strong>QuickBooks Online</strong>, only for Customers who explicitly connect their account for
            accounting synchronisation.
          </li>
          <li>
            <strong>Law enforcement or regulators</strong>, where we are legally required to disclose data.
          </li>
        </ul>

        <h2>5. How long we keep data</h2>
        <p>
          We retain data for as long as a Customer&rsquo;s account is active, plus a limited period afterwards for
          legal, accounting, and dispute-resolution purposes. Following account termination, a Customer&rsquo;s data
          remains available for export for 30 days, after which it is deleted or anonymized, except where longer
          retention is required by law (for example, financial records).
        </p>

        <h2>6. Your rights</h2>
        <p>Under the Data Protection Act, 2019, you have the right to:</p>
        <ul>
          <li>be informed of how your data is being used;</li>
          <li>access the personal data we (or a Customer, via us) hold about you;</li>
          <li>request correction of inaccurate or outdated data;</li>
          <li>request deletion of your data, subject to our legal retention obligations;</li>
          <li>object to or restrict certain processing;</li>
          <li>request a copy of your data in a portable format; and</li>
          <li>lodge a complaint with the Office of the Data Protection Commissioner (ODPC), Kenya.</li>
        </ul>
        <p>
          If your data was entered into the Platform by a landlord or agent (for example, as their tenant), please
          contact them directly in the first instance, as they control that data. You may also contact us using the
          details below and we will assist or forward your request.
        </p>

        <h2>7. Security</h2>
        <p>
          We use industry-standard measures to protect personal data, including encrypted connections (HTTPS),
          hashed passwords, and role-based access controls that limit who within an organization can see what data.
          No system is completely secure, and we encourage Customers to use strong, unique passwords and to review
          who has access to their account.
        </p>

        <h2>8. Children&rsquo;s data</h2>
        <p>The Platform is intended for business use by adults and is not directed at children. We do not knowingly collect personal data from children.</p>

        <h2>9. Changes to this policy</h2>
        <p>
          We may update this policy from time to time. Material changes will be reflected by updating the &ldquo;Last
          updated&rdquo; date above.
        </p>

        <h2>10. Contact us</h2>
        <p>
          For any question about this policy or your data, contact us at:
          <br />
          <strong>Reinstrade / Robust Rental Platform</strong>
          <br />
          Email: <a href="mailto:reinstrade@gmail.com">reinstrade@gmail.com</a>
          <br />
          Registered address: [registered business address]
          <br />
          Phone: [business phone number]
          <br />
          ODPC registration number: [to be added once registered with the Office of the Data Protection Commissioner]
        </p>
      </article>
    </div>
  );
}
